#! /bin/dash

pgrep -x sxhkd > /dev/null || sxhkd & # run sxhkd
bspc monitor -d I II III IV V VI VII VIII IX X # workspaces
bspc config border_width         2 # window borders
bspc config window_gap           10 # window gaps
bspc config split_ratio          0.50 # split ratio
